<?php
/** @var $this Perpetto_Perpetto_Block_Adminhtml_System_Config_Form_Recommendations */
?>
<div class="perpetto">
    <?php echo $this->getHeaderHtml(); ?>
    <?php if ($this->showLinks()): ?>
        <table cellpadding="0" cellspacing="0" width="100%">
            <tr>
                <td style="padding-right: 10px;">
                    <div class="entry-edit entry-edit-box">
                        <div class="entry-edit-head">
                            <h4><?php echo $this->__('Dashboard'); ?></h4>
                        </div>
                        <div class="fieldset">
                            <p><?php echo $this->__('View your Dashboard to see how Perpetto is helping your store.'); ?></p>
                            <a class="button" href="<?php echo $this->getDashboardUrl() ?>"
                               target="_blank"><?php echo $this->__('View Your Perpetto Dashboard'); ?></a>
                        </div>
                    </div>
                </td>
                <td style="padding-right: 10px; padding-left: 10px;">
                    <div class="entry-edit entry-edit-box">
                        <div class="entry-edit-head">
                            <h4><?php echo $this->__('Ask-Us-Anything Support'); ?></h4>
                        </div>
                        <div class="fieldset">
                            <p><?php echo $this->__('Ask us anything you might need to know. We are here to help.'); ?></p>
                            <a class="button" href="<?php echo $this->getContactsUrl() ?>"
                               target="_blank"><?php echo $this->__('Get In Touch'); ?></a>
                        </div>
                    </div>
                </td>
                <td style="padding-left: 10px;">
                    <div class="entry-edit entry-edit-box">
                        <div class="entry-edit-head">
                            <h4><?php echo $this->getBillingTitle() ?></h4>
                        </div>
                        <div class="fieldset">
                            <p><?php echo $this->getBillingText() ?></p>
                            <a class="button" href="<?php echo $this->getBillingUrl() ?>"
                               target="_blank"><?php echo $this->getBillingButtonText() ?></a>
                        </div>
                    </div>
                </td>
            </tr>
        </table>

        <div class="clear"></div>
    <?php endif ?>
    <?php if ($this->showSlots()): ?>
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4><?php echo $this->__('Recommendation Slots'); ?></h4>
            </div>
            <div class="fieldset">
                <p class="box-left"><?php echo $this->__('Here you can see what recommendations are installed. You can see how they will look with the' .
                        '"Preview" button and change their algorithm, number of displayed items or styling in the Perpetto ' .
                        'administration area using the "Edit Recommendations" button'); ?></p>

                <div class="box-right align-right">
                    <?php $url = $this->getRandomProductPreviewUrl(); ?>
                    <?php if ($url != ''): ?>
                        <a class="button" href="<?php echo $url; ?>"
                           target="_blank"><?php echo $this->__('Preview'); ?></a>
                    <?php endif; ?>
                    <a class="button" href="<?php echo $this->getRecommendationsUrl(); ?>"
                       target="_blank"><?php echo $this->__('Edit Recommendations'); ?></a>
                </div>

                <div class="clear"></div>

                <?php $pages = $this->getGroupedSlots(); ?>
                <?php foreach ($pages as $page => $slots): ?>
                    <?php
                    $pageLabel = ucwords(str_replace('_', ' ', $page));
                    $slotsCount = count($slots);
                    ?>
                    <table class="perpetto-slots" cellpadding="0" cellspacing="0" width="100%">
                        <tbody>
                        <tr>
                            <th rowspan="<?php echo $slotsCount + 1 ?>"><?php echo $pageLabel ?></th>
                            <th><?php echo $this->__('Slot Title'); ?></th>
                            <th><?php echo $this->__('Recommendation Algorithm'); ?></th>
                            <th><?php echo $this->__('Slot Container'); ?></th>
                        </tr>
                        <?php foreach ($slots as $slot): /** @var $slot Perpetto_Perpetto_Model_Slot */ ?>
                            <?php
                            $format = '<div class="ptto-rec-slot-token" data-ptto-token="%s"></div>';
                            $containerHtml = sprintf($format, $slot->getToken());
                            $algorithmName = ucwords(str_replace('_', ' ', $slot->getEngineName()));
                            ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($slot->getTitle()) ?></td>
                                <td><?php echo $this->escapeHtml($algorithmName) ?></td>
                                <td><?php echo $this->escapeHtml($containerHtml); ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>

                <?php endforeach; ?>
            </div>
        </div>
    <?php endif ?>
    <?php echo $this->getChildHtml('form_after'); ?>
</div>
<script type="text/javascript">
    $$('#content .content-header button').each(function (item) {
        item.remove();
    });
</script>
